kind: pipeline
type: docker
name: release
steps:
  - name: build and push image
    image: plugins/docker
    settings:
      repo: cruii/drone-feishu
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag
---
kind: pipeline
type: docker
name: ci
steps:
  - name: go-build
    image: golang:1.21-alpine
    commands:
      - GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -o drone-ci-feishu .
  - name: notify
    image: cruii/drone-feishu
    pull: always
    settings:
      user_id:
        from_secret: user_id
      chat_id:
        from_secret: chat_id
      app_id:
        from_secret: app_id
      app_secret:
        from_secret: app_secret
trigger:
  event:
    include:
      - push
      - pull_request
  branch:
    exclude:
      - main